apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  # Base resources embedded in overlay for Fleet path resolution
  # Note: grafana namespace created by Loki stack
  - promtail-helmchart.yaml

commonLabels:
  app: promtail
  managed-by: gitops
  cluster: nprd-apps