apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - namespace.yaml
  - loki-helmchart.yaml
  - promtail-helmchart.yaml
  - grafana-helmchart.yaml
  - prometheus-helmchart.yaml
  - loki-ingress.yaml
  # Vector syslog receiver for UniFi CEF ingestion
  - vector-configmap.yaml
  - vector-deployment.yaml
  - vector-syslog-service.yaml
  - vector-ingress.yaml

commonLabels:
  app: loki
  managed-by: gitops
