apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - namespace.yaml
  - loki-helmchart.yaml
  - promtail-helmchart.yaml
  - grafana-helmchart.yaml

commonLabels:
  app: loki
  managed-by: gitops
