apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: managed-syslog

resources:
  # Base resources embedded in overlay for Fleet path resolution
  # Note: namespace.yaml removed - managed-syslog namespace will be created by base
  - loki-helmchart.yaml
  - promtail-helmchart.yaml
  - grafana-helmchart.yaml
  - loki-ingress.yaml
  # Vector syslog receiver for UniFi CEF ingestion
  - vector-configmap.yaml
  - vector-deployment.yaml
  - vector-syslog-service.yaml

commonLabels:
  app: loki
  managed-by: gitops
