apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: managed-tools

resources:
  # Include overlay kustomization which references base
  - overlays/nprd-apps

commonLabels:
  app: harbor
  managed-by: gitops
