apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: managed-syslog

resources:
  - prometheus-agent-helmchart.yaml
  - node-exporter-helmchart.yaml
  - kube-state-metrics-helmchart.yaml

commonLabels:
  app: prometheus-agent
  managed-by: gitops
  cluster: cluster-b