# Node Exporter Helm Chart Configuration - cluster-b Overlay
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-node-exporter
  namespace: managed-syslog
spec:
  chart: prometheus-node-exporter
  repo: https://prometheus-community.github.io/helm-charts
  targetNamespace: managed-syslog
  valuesContent: |-
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    service:
      port: 9100
      targetPort: 9100
    image:
      registry: harbor.dataknife.net
      repository: dockerhub/prom/node-exporter
      tag: "v1.7.0"