apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: managed-syslog

resources:
  - promtail-helmchart.yaml

commonLabels:
  app: promtail
  managed-by: gitops
  cluster: poc-apps