apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - namespace.yaml
  - promtail-helmchart.yaml

commonLabels:
  app: promtail
  managed-by: gitops
  cluster: prd-apps